### ISSUE TITLE
Broken logic after recent changes

### ISSUE THREAD

**Issue by arkadiuszwojcik** [failwyn/WebCompiler#1]
Didn't test that but from code analysis looks like there is bug in file: LessCompiler.cs 

```
if (options.IECompat)
  arguments += " --ie-compat";

if (options.StrictUnits)
  arguments += " --strict-units=on";
```

was changed to:

```
if (options.IECompat)
  //arguments += " --ie-compat";

if (options.StrictUnits)
   arguments += " --strict-units=on";
```

which translates to:

```
if (options.IECompat)
{
    if (options.StrictUnits)
    arguments += " --strict-units=on";
}
```

so line:

`if (options.IECompat)`

should also be commented out

Btw: Thanks for your effort to port this project to VS2022

**Comment by failwyn** [comment]
Thanks for that! I'll get it addressed and upload a new version this weekend.
