### ISSUE TITLE
Sass compiler ignores "indentWidth" default setting

### ISSUE THREAD

**Issue by CoKorum** [failwyn/WebCompiler#18]
### Installed product versions
- Visual Studio: Community 2022
- This extension: version 1.14.2

### Description
Dart-Sass ignores the "indentWidth" default setting for sass. When it is set to 4, the output still put 2 spaces.

### Steps to recreate
1. Have "indentWidth": 4 in the "sass" node of the "compilerconfig.json.default" file
2. Compile a file using Dart-Sass (default engine it seems)

### Current behavior
Outputted CSS has an indentation of 2 spaces.

### Expected behavior
Outputted css should have an indentation of 4 spaces according to the default setting.

**Comment by failwyn** [comment]
It doesn't look like Dart-Sass supports the indentWidth option.

[Dart Sass Command-Line Interface](https://sass-lang.com/documentation/cli/dart-sass)
