### ISSUE TITLE
Missing Newtonsoft.Json.dll from VSIX

### ISSUE THREAD

**Issue by EddieGreen** [failwyn/WebCompiler#2]
### Installed product versions
```Microsoft Visual Studio Enterprise 2022 Preview
Version 17.0.0 Preview 3.1
VisualStudio.17.Preview/17.0.0-pre.3.1+31612.314
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Web Compiler   1.13.002
Compiler for LESS, Sass and CoffeeScript files
```
### Description
VSIX does not install Json library.

Using Task Runner, produces the following error:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
   at WebCompiler.ConfigHandler.GetConfigs(String fileName)
   at WebCompiler.Program.GetConfigs(String configPath, String file) in W:\Git\Light Speed Solutions\WebCompiler\src\WebCompiler\Program.cs:line 55
   at WebCompiler.Program.Main(String[] args) in W:\Git\Light Speed Solutions\WebCompiler\src\WebCompiler\Program.cs:line 14
```

Adding this library directly to vsix install path resolves error - [download](https://www.nuget.org/packages/Newtonsoft.Json/9.0.1)

**Comment by failwyn** [comment]
Do you know if this works with the 2019 version of WebCompiler?

**Comment by EddieGreen** [comment]
### 2019 Installation
Microsoft Visual Studio Enterprise 2019
Version 16.11.1
VisualStudio.16.Release/16.11.1+31613.86
Microsoft .NET Framework
Version 4.8.04084

Web Compiler   1.12.394
Compiler for LESS, Sass and CoffeeScript files

Works fine on this, always has.

**Comment by failwyn** [comment]
Would you mind helping me out with a sample project or a walk though of how to set this up?

**Comment by EddieGreen** [comment]
Sure. What do you want me to do?

**Comment by failwyn** [comment]
If you have a simple project that you can upload and provide a link to, I can use that; otherwise just a walk through of what I have to add to a project to get WebCompiler set up in Task Runner would be great.

**Comment by failwyn** [comment]
Scratch that, I got it set up, restarting Visual Studio fixed the Task Runner Explorer; I'll get this fixed and let you know when I upload a new version.

**Comment by failwyn** [comment]
I just uploaded a new version that fixes this issue; having trouble with OAuth token, so the commit hasn't been pushed yet. thanks for the report.

**Comment by EddieGreen** [comment]
Nicely! Thanks
