### ISSUE TITLE
Update BuildWebCompiler nuget package

### ISSUE THREAD

**Issue by dlipdhunter** [failwyn/WebCompiler#22]
### Installed product versions
- Visual Studio: 2022 Professional
- This extension: 1.14.2

### Description
The extension is working great for development, but the nuget package that is used for enabling compilation on build systems outside of visual studio is not updated. Hence the build fails when any new features of autoprefixer are used.

### Steps to recreate
1. Set "autoPrefix": ">= 0.5%, last 2 major versions, not dead, Chrome >= 60, Firefox >= 60, Firefox ESR, iOS >= 12, Safari >= 12, not Explorer <= 11" in sass section of the compilerconfig.json.defaults file.
2. Build the project using MSBuild 17.

### Current behavior
Build fails with the following error,
WebCompiler error 0: Browserslist: caniuse-lite is outdated. Please run next command `npm update`

### Expected behavior
Scss files should get compiled and build successfully with autoPrefix: ">= 0.5%, last 2 major versions, not dead, Chrome >= 60, Firefox >= 60, Firefox ESR, iOS >= 12, Safari >= 12, not Explorer <= 11".

**Comment by failwyn** [comment]
This should be fixed in 1.14.3; I don't have a code signing certificate, so hopefully that doesn't break the functionality further...
