### ISSUE TITLE
One of my .scss files is not compiled on build

### ISSUE THREAD

**Issue by cawise** [failwyn/WebCompiler#26]
### Installed product versions
- Visual Studio: 2022 Enterprise
- This extension: 1.14.2
 
### Description
One of my .scss files does not automatically recompile while the others do. My folder contains four .scss files:
- _variables.scss
- bootstrap.scss
- kendo.scss
- site.scss
 
bootstrap.css/bootstrap.min.css and and site.css/site.min.css are automatically generated, but kendo.css/kendo.min.css are not.
 
This is the contents of kendo.scss:
 
```
@import "../css/_variables.scss";
 
$kendo-picker-hover-bg: #fff;
 
@import "../lib/kendo-theme-bootstrap/dist/all";
```
 
Trying to build the solution fails with a strange error:
WebCompiler error 0: Invalid CSS after "...-header-border,": expected expression (e.g. 1px, bold), was ");"
 
The build succeeds without error if kendo.css already exists, even if it's an empty file. However, the build does not generate kendo.css/kendo.min.css.
 
If I right-click on kendo.scss and choose Web Compiler > Re-compile file or right-click on compilerconfig.json and choose Web Compiler > Re-compile all files, kendo.css/kendo.min.css are correctly generated without issue. Or if I make a change to kendo.scss and save, it gets recompiled automatically. But it's not being compiled on build like the other .scss files are. Here's the contents of compilerconfig.json:
 
```
[
  {
    "outputFile": "wwwroot/css/bootstrap.css",
    "inputFile": "wwwroot/css/bootstrap.scss"
  },
  {
    "outputFile": "wwwroot/css/kendo.css",
    "inputFile": "wwwroot/css/kendo.scss"
  },
  {
    "outputFile": "wwwroot/css/site.css",
    "inputFile": "wwwroot/css/site.scss"
  },
  {
    "outputFile": "Shared/TopNav.razor.css",
    "inputFile": "Shared/TopNav.razor.scss"
  }
]
```
 
### Steps to recreate
1. Delete the *.css and *.min.css files.
2. bootstrap.scss and site.scss are automatically recompiled, while kendo.scss is not
3. Build fails
4. Recompile kendo.scss manually
5. kendo.scss is recompiled and build succeeds
 
### Current behavior
kendo.scss is only recompiled when triggered manually.
 
### Expected behavior
kendo.scss is automatically recompiled and compiled on build like the other .scss files in the folder.

**Comment by failwyn** [comment]
It sounds like there's an be an error in the kendo style sheet, if you can provide a sample project, I can take a look at it for you.

**Comment by cawise** [comment]
Yeah, that was my first thought, but then I wouldn't think it should compile when I manually trigger it either.

Is there any Web Compiler log where I could see what it's doing when automatically recompiling in the background? Maybe there's a silent error somewhere.

Thanks for the quick reply. I'll try to distill down a smaller project demonstrating the issue.

**Comment by failwyn** [comment]
Good observation! This may actually be related to #22, I need to figure out how to publish the updated package to Nuget since the CompileOnBuild option uses the Nuget Package instead of the Vsix. I'll look into this over the weekend; I've never published a nuget package, I probably have to rename the package as well to differentiate it from Mads' nuget.

**Comment by failwyn** [comment]
This should be fixed in 1.14.3; let me know if this fixes the issue for you.

**Comment by cawise** [comment]
Updated extension to 1.14.3 and it does install BuildWebCompiler2022 1.14.3, but now none of my .scss get compiled on build at all. They are successfully compiled when I click Re-compile from the context menu or change a file and save it, but none of them get compiled on build.

One time, I received an error after seemingly not having touched Visual Studio for a minute or two. I was presented with a dialog saying, "_There is an error in the compilerconfig.json file. This could be due to a change in the format after this extension was updated._"

And down in the Output window:

```
2/11/2022 3:17:32 PM: System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at WebCompiler.SassDependencyResolver.UpdateFileDependencies(String path) in W:\Git\Light Speed Solutions\WebCompiler\src\WebCompiler\Dependencies\SassDependencyResolver.cs:line 71
   at WebCompiler.DependencyResolverBase.GetDependencies(String projectRootPath) in W:\Git\Light Speed Solutions\WebCompiler\src\WebCompiler\Dependencies\DependencyResolverBase.cs:line 57
   at WebCompiler.ConfigFileProcessor.SourceFileChanged(String configFile, String sourceFile, String projectPath, HashSet`1 compiledFiles) in W:\Git\Light Speed Solutions\WebCompiler\src\WebCompiler\Config\ConfigFileProcessor.cs:line 125
   at WebCompilerVsix.CompilerService.<>c__DisplayClass7_0.<SourceFileChanged>b__0(Object o) in W:\Git\Light Speed Solutions\WebCompiler\src\WebCompilerVsix\CompilerService.cs:line 101
```

I have not reproduced that exact error again since, so I'm not sure what triggered it. My compilerconfig.json is unchanged from my original post above.

**Comment by cawise** [comment]
If I go into Task Runner Explorer and add bindings for each of the files, this adds a compilerconfig.json.bindings to my project and the files are compiled on build. However, often during build I will receive at least one prompt that "Web Compiler has stopped working."

Windows Event log contains an error similar to the one above.

**Comment by failwyn** [comment]
I’ll look into this; it worked for me when I tested before uploading the nee extension, nit sure what could have changed.

**Comment by failwyn** [comment]
I’ll take a look at that on Monday; I didn’t want to leave a bad release out there for the weekend.

**Comment by failwyn** [comment]
I found a few issues with the src/WebCompiler/MSBuild/BuildWebCompiler.targets file (paths to the exe and dll), but even after fixing them, I haven't gotten it to work yet; I'll keep looking at it, but I would love some advice if anyone has any experience with nuget packages with MSBuild targets.

**Comment by itcasinosolutions** [comment]
FWIW, I spent quite a bit of time trying to figure out why this particular NuGet package does not compile my SASS files on build, but the original one does.  I had noticed that the path in the msbuild targets file was pointing to the wrong place, fixed that, but to no avail.  There was one other peculiarity that I found, but could not for the life of me figure out how this was being set.

Specifically, in my project's obj folder, there is a file:

`<Project Name>.csproj.nuget.g.targets`

which, when using the 'original' version of BuildWebCompiler (https://github.com/madskristensen/WebCompiler), has the following line:

`<Import Project="$(NuGetPackageRoot)buildwebcompiler\1.12.405\build\BuildWebCompiler.targets" Condition="Exists('$(NuGetPackageRoot)buildwebcompiler\1.12.405\build\BuildWebCompiler.targets')" />`

This line is **missing** after installing BuildWebCompiler2022.

Sorry that I can't provide any more insight on this...

**Comment by failwyn** [comment]
Thanks for this! I found some links that could be promising to fix this issue! I had to do a quick release to fix a backwards compatibility issue today, but I will try fixing this issue again later in the week.

**Comment by failwyn** [comment]
That did it!!! I'll get a new version out as soon as I'm sure today's release is stable, in the meantime, if you go to

%userprofile%\.nuget\packages\buildwebcompiler2022\1.14.6\build

and rename BuildWebCompiler.targets to BuildWebCompiler2022.targets then Disable and Enable Build on compile, it will start working as expected.

**Comment by itcasinosolutions** [comment]
Love it! I was just about to post that I fixed it with a rename of the .targets file!  Great minds must think alike, no?

Thanks for keeping this project alive!
