### ISSUE TITLE
Recompiling Sass after editing a file doesn't work 

### ISSUE THREAD

**Issue by hatakealex** [failwyn/WebCompiler#28]
### Installed product versions
- Visual Studio: 2022 community
- This extension: 1.14.3

### Description
Recompiling Sass after editing a file doesn't work 

### Steps to recreate
1. Create sass file
2. Re-compile - success: css file and minified file are created side by side
3. edit sass file 
4. recompilation fails: style files remain old unchanged. if you delete them and click recompile again, then old style files or empty ones are created

### Current behavior
files do not change 

### Expected behavior
compiled files must contain new code 

I use a translator. sorry if something is not clear

**Comment by hatakealex** [comment]
I found a bad solution:
delete files: compiled.css, compiled.min.css, compilerconfig.json, compilerconfig.json.defaults

then recompile.

But this is not the expected behavior of the plugin.

**Comment by failwyn** [comment]
This appears to be related to the regex change I did to support @use and @forward; I'll try to have this fixed or rolled back today.

**Comment by failwyn** [comment]
I think I found the issue... I've never been good with regular expressions... I'm gonna test for about an hour then upload a new version.

**Comment by hatakealex** [comment]
I want to thank you very much for the plugin.  It saves a lot of time and is very useful in the case of, for example, Web forms - when the sass is not compiled automatically when compiling.  Thanks to you, I learned sass and realized that it is very good

**Comment by failwyn** [comment]
I just uploaded 1.14.4; this should fix the issue.

**Comment by hatakealex** [comment]
Now the behavior is like this, I will clarify my actions:
Run studio and open project.
I have a style.scss file. I make changes, save scss. 
I right click on it > Web compilation > Re-compile file. 

At the bottom of the studio, the status bar shows "Compiling...". Status does not change over time . If you click the mouse in any part of the program, then this status becomes "ready". The compiled files remain the same. But after a while they change to and compile correctly themselves. I assume you are using a background task.
If re-introduce changes to the style.cscc and recompile, the process takes a second or two and progress is displayed in the status bar. Everything is correct.

**Comment by failwyn** [comment]
Studio compiles it in the background, I have a lot of files on mine, it takes about 30 seconds to finish compiling. If you change the file and just let it do its thing, does it eventually say successful? Mine is working as expected with 1.14.4.

**Comment by hatakealex** [comment]
Everything is working.  You just need a correct display that the compilation process is in progress.  Thank you for your quick replies.
