### ISSUE TITLE
"Enable compile on build..." not working

### ISSUE THREAD

**Issue by core1915** [failwyn/WebCompiler#3]
### Installed product versions
Microsoft Visual Studio Community 2022 Preview (64-bit)
Version 17.0.0 Preview 3.1

Web Compiler   1.13.2

### Description
Right click on "compilerconfig.json" -> Web compiler -> Enable compile on build... asks me to install NuGet package, clicking "Yes" and than got the error below. On VS2019 this feature works.

![image](https://user-images.githubusercontent.com/90519631/132953577-6d0f4bd9-6e42-412a-b2a4-45d20ae47844.png)

**Comment by ahwm** [comment]
I ran into this as well. I "fixed" it by just manually installing the latest version of the package - https://www.nuget.org/packages/BuildWebCompiler/ (currently 1.12.405)

`PM> Install-Package BuildWebCompiler` did the trick

**Comment by failwyn** [comment]
I found the cause of this issue, I'll try to publish a new version by tomorrow afternoon.

**Comment by failwyn** [comment]
uploaded a new version to the marketplace, I'm still having issues with OAUTH, will push the code changes as soon as they are resolved
