### ISSUE TITLE
SCSS values are not compiled in css variables

### ISSUE THREAD

**Issue by mastermehdi** [failwyn/WebCompiler#34]
### Installed product versions
- Visual Studio: 2022 Enterprise
- This extension: 1.14.4

### Description
SCSS values are not compiled in css variables

### Current behavior
$scss-color-value: #ffffff
--css-variable: $scss-color-value;
//After Rendering
--css-variable: $scss-color-value;

### Expected behavior
$scss-color-value: #ffffff
--css-variable: $scss-color-value;
//After Rendering
--css-variable: #ffffff;

**Comment by mm201** [comment]
I think this is because of the switch to dart-sass and https://sass-lang.com/documentation/breaking-changes/css-vars
Really painful breaking change IMO.
