### ISSUE TITLE
VS 17.1.1 SCSS Compile Error

### ISSUE THREAD

**Issue by brenasmith** [failwyn/WebCompiler#35]
### Installed product versions
- Visual Studio: Community 17.1.1
- This extension: 2.9.3

### Description
When compiling SCSS files the CSS file is not generated and this error occurs...

"Unexpected character encountered while parsing value: [. Path 'loadPaths', line 3, position 16"

This error started after upgrading VS to 17.1.1 from previous latest version.

Same error happens in another solution that was also working fine before the VS upgrade.

Any help appreciated!

**Comment by doddy22** [comment]
Also started getting this issue today for scss files. Though I'm still on VS 17.0.5

**Comment by JSystemsTech** [comment]
Confirmed that I also am getting this issue after upgrading VS to 17.1.1

**Comment by fabioparra** [comment]
Same here... VS 17.0.0

**Comment by losingrose** [comment]
Same here VS 17.0.5
After I update the latest version 1.14.5.
Where can I download old version?

**Comment by fabioparra** [comment]
Thanks @losingrose. I edited compilerconfig.json.defaults file and changed the "loadPaths" value of "sass" object from [] to "".
Its documented here: [https://github.com/failwyn/WebCompiler/blob/master/CHANGELOG.md](url)

**Comment by ThreeSevenths** [comment]
I had to adjust two properties in my sass section: style changed to "expanded", and loadPaths to "" as @fabioparra mentions. I did not have to adjust anything else or make a nodesass section.
