### ISSUE TITLE
VS2022  Right Click "Web Compiler" menu does not show up.

### ISSUE THREAD

**Issue by tlydon3** [failwyn/WebCompiler#38]
### Installed product versions
- Visual Studio: 2022 Community
- This extension: 1.14.7

### Description
The  "Web Compiler" menu does not show up on right click  of any file, including compilerconfig.json

### Steps to recreate
1. Right click on compilerconfig.json or .scss file

### Current behavior
Not menu showing

### Expected behavior
Expecting menu like this image:
https://github.com/failwyn/WebCompiler/blob/master/art/contextmenu-compile.png

**Comment by osoviejo** [comment]
I was seeing the same behavior.  I have extensively customized the VS menu/toolbar/context configuration, although made no explicit changes to the Web Compiler entries.  I reset the customizations to default, and the web compiler started showing up in all the expected ways.  The VS menu customization infrastructure is, in my experience, a mess of bugs and bad behavior.  Add this to the list.

**Comment by failwyn** [comment]
@tlydon3 Does resetting the VS menus as described above resolve the issue for you?

@osoviejo Thanks for the info! The menus in VS are a nightmare to work with!

**Comment by tlydon3** [comment]
It turned out to be an issue with solution originally created in VS2019 and then opened with VS2022. After reinstalling Web Compiler it started working.

**Comment by failwyn** [comment]
Glad to hear it’s working; Thanks for updating the issue.

**Comment by VictorioBerra** [comment]
Wanted to say, my extension was set to disabled. Going to Extensions -> Installed -> Web Compiler and clicking "Enable" fixed it.

No idea how it became disabled...
