### ISSUE TITLE
Upgrade issues: Long relative path needed adjusted from prior 2019 WebCompiler and duplicate nuget package

### ISSUE THREAD

**Issue by zacuke** [failwyn/WebCompiler#44]
After upgrading from the previous of WebCompiler,

We have a scss file with an @import path like this:
@import "../../../../../lib/bootstrap/scss/bootstrap.scss";

I had to edit all of them to include an additional ../
@import "../../../../../../lib/bootstrap/scss/bootstrap.scss";

Also I  had to manually uninstall the old WebCompiler nuget package and it would be nice if this one automatically removed what is now a duplicate package and targets.

Thank you very much for getting this updated to 2022!

**Comment by failwyn** [comment]
Can you provide a sample solution that worked in 2019 with less ../‘s? I have a massive number of scss files that import using relative paths and haven’t had any that required changes.

**Comment by zacuke** [comment]
No problem, here is a repro project: [temp2.zip](https://github.com/failwyn/WebCompiler/files/8524362/temp2.zip)

Assuming both vs2019 and vs2022 have the respective WebCompiler extension already installed

1. Extract the zip but maintain the folder structure (Find sln inside zip at \temp2\ReproOuter\level1\level2\repro\Repro)
2. Opens in 2019 and I can make a change to the scss file and it regenerates the output css.
3. Opens in 2022 but as soon as I make a change to the scss file and it triggers auto-recompile, I see the error in the attached screenshot.

![bd2022ed](https://user-images.githubusercontent.com/2529117/164299108-66bbd14c-2ea4-43c8-bf55-1d7627afb975.png)

**Comment by failwyn** [comment]
Based on the sample project, you need to go up 6 directories to get to the temp2 directory that contains your lib directory; I don't know why this worked in the previous version with incorrect relative paths (going up 5 directories lands you in the ReproOuter directory); unless I'm missing something, it appears to be working correctly in the current version.

**Comment by zacuke** [comment]
The old code must be trying multiple alternate source paths when resolving the relative pathing. I'll close with comment, at least this discussion is here if anyone else gets hung up on this particular oddity.
