### ISSUE TITLE
Automatic compiling for javascript files

### ISSUE THREAD

**Issue by reneduesmann** [failwyn/WebCompiler#5]
### Installed product versions
- Visual Studio: 19, 22 Preview
- This extension: 1.13.4

### Description
Include auto compile for .js files.

### Current behavior
At the moment, i must explicity say "Re-compile file" or save the compilerconfig.json file, to compile javascript files.

### Expected behavior
When i save a javascript file, that the file will be compiled.

**Comment by memepuppy** [comment]
The problem is in SourceFileCreationListener.cs, add [ContentType("TypeScript")] and it will work.
![image](https://user-images.githubusercontent.com/56789821/138083023-4d5a1ae8-94a8-486a-bb9e-37082022aee1.png)

**Comment by failwyn** [comment]
Sorry for the long delay on this, crunch season snuck up on me; Does anyone know how the ContentTypeAttribute works? How does it associate the type to the file opened in the editor, and why doesn't "javascript" map to *.js files?
