### ISSUE TITLE
[ARM64] Plugin don't start in Visual Studio 17.4 (ARM64)

### ISSUE THREAD

**Issue by py-nux** [failwyn/WebCompiler#51]
### Installed product versions
- Visual Studio: 2022 Community Preview 17.4 ( ARM64 Installation)
- This extension: .14.8.1

### Description
Extension don't start in ARM64 of Visual Studio 
in log : 
CreateInstance failed for package [WebCompilerInitPackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;file:///c:\users\pynux\appdata\local\microsoft\visualstudio\17.0_b2995c49\extensions\oucyl340.vrz\WebCompilerVsix.dll&apos; or one of its dependencies. Tentative de chargement d&#x2019;un programme de format incorrect.&#x000D;&#x000A;System.BadImageFormatException: Could not load file or assembly &apos;file:///c:\users\pynux\appdata\local\microsoft\visualstudio\17.0_b2995c49\extensions\oucyl340.vrz\WebCompilerVsix.dll&apos; or one of its dependencies. Tentative de chargement d&#x2019;un programme de format incorrect.&#x000D;&#x000A;File name: &apos;file:///c:\users\pynux\appdata\local\microsoft\visualstudio\17.0_b2995c49\extensions\oucyl340.vrz\WebCompilerVsix.dll&apos;&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;
<img width="595" alt="Capture d’écran 2022-08-25 à 18 09 37" src="https://user-images.githubusercontent.com/8087648/186715773-8ecf6326-952d-4b76-8822-d444bc37d70e.png">

### Steps to recreate
1.Install pextensions
2. Restart Visual Studio
3. Extension don't start missing

**Comment by failwyn** [comment]
I don't have access to an ARM64 machine to replicate this, open to pull requests if anyone would like to investigate it.

**Comment by failwyn** [comment]
Keep an eye out for a new version here, I can't test it, so I won't upload it to the VS Marketplace until you report back. I'll try to get it uploaded in the next day or so.

**Comment by failwyn** [comment]
It appears there are some more challenges with ARM64 support, so I'm going to work on one extension at a time, once that one is working, I'll apply everything I've learned here. Keep and eye on [https://github.com/failwyn/BundlerMinifier/issues/18#issue-1531354849](https://github.com/failwyn/BundlerMinifier/issues/18#issue-1531354849) for progress updates.

**Comment by failwyn** [comment]
Here's a first attempt at arm64 support for WebCompiler, anyone willing to test, please let me know details of any issues you encounter.
[WebCompilerVsix.zip](https://github.com/failwyn/WebCompiler/files/11077605/WebCompilerVsix.zip)

**Comment by BenDTU** [comment]
@failwyn That link gives a 401 error for me.

**Comment by jacklawry** [comment]
The link works for me - Just testing it now.

**Comment by jacklawry** [comment]
It seems to work!

**Comment by jacklawry** [comment]
I made a change to my scss file  it compiled my css file (.css & .min.css)

**Comment by BenDTU** [comment]
Ah yeah that's downloaded ok for me, I might have jumped in a bit too quickly. That looks to be working for me too.

**Comment by failwyn** [comment]
Awesome!! Does anyone have access to an x64 machine with a Visual Studio version lower than 17.4 to test if it works on 17.0, 17.1, 17.2, or 17.3?

// getting complaints that Bundler & Minifier no longer work on earlier versions of Visual Studio 2022...

**Comment by ronmichael** [comment]
I can also confirm that it works on VS 17.5.0 ARM, in Parallels on a Mac M2 processor. It's so great to have this back again!

**Comment by failwyn** [comment]
Glad to hear it! I'll publish it to the Visual Studio Marketplace shortly!
