### ISSUE TITLE
:has(...) selector not minifying correctly

### ISSUE THREAD

**Issue by BalazsLaszloDyntell** [failwyn/WebCompiler#56]
### Installed product versions
- Visual Studio: Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.1.1
- This extension: 1.14.8

### Description
After the :has(...) selector in the minified css there is missing a space character
SCSS input:
```
.container:has(> div[controller="Inventory"][view="Edit"]) {
    div#items {
        .dx-selection {
            background-color: rgba(53,128,183, .1) !important;
        }
    }
}
```
Minified output:
`.container:has(> div[controller=Inventory][view=Edit])div#items .dx-selection{background-color:rgba(53,128,183,.1)!important;}`

### Steps to recreate
1. Write code with :has selector
2. compile and minify
3. minified code not working correctly

### Current behavior
After the :has(...) selector in the minified css there is missing a space character

### Expected behavior
Wrong: `.container:has(> div[controller=Inventory][view=Edit])div#items .dx-selection{background-color:rgba(53,128,183,.1)!important;}`
Good: `.container:has(> div[controller=Inventory][view=Edit]) div#items .dx-selection{background-color:rgba(53,128,183,.1)!important;}`

**Comment by alesmasiar** [comment]
I've also stumbled upon this. 

After some research I found this is a bug in a package this project is using for minification. 

It's using NUglify 1.5.12, which is a version from 2018. I've tried upgrading the package to the latest version (1.20.3), built and installed the WebCompiler from this repo and it seems to have fixed the issue.

Seems to be quite an easy fix without any noticeable breaking changes. 

@failwyn would it be possible to upgrade the package a release a new build?
