### ISSUE TITLE
Build error when upgrading to 1.14.9

### ISSUE THREAD

**Issue by cryo75** [failwyn/WebCompiler#59]
### Installed product versions
- Visual Studio: 2022 Community
- This extension: 1.14.9

### Description
Upgraded from 1.14.8 to 1.14.9 (the Nuget package and the Extension) and I get the error shown in the image when building the project.

### Current behavior
Error when building the project.

### Expected behavior
No build error should occur.

![image](https://user-images.githubusercontent.com/3060986/204845230-c291c1a7-e018-4138-b018-01249ce6d2d6.png)

**Comment by failwyn** [comment]
@cryo75 Thanks for the heads up, toggle CompileOnBuild on and off and it should pull the updated nuget package.

For some reason, when building the nuget package Visual Studio is creating a net48 folder with the exe and a net4.8 folder with the dlls, I have to manually move the exe to the net4.8 folder after creating the nuget package... If anyone has any idea why this is happening, it would greatly simplify the release process.

**Comment by cryo75** [comment]
Thanks for the quick reply. No need for the above workaround with the latest fix (1.14.9.1)
