### ISSUE TITLE
Javascript compile output does not work

### ISSUE THREAD

**Issue by reneduesmann** [failwyn/WebCompiler#6]
### Installed product versions
- Visual Studio: 19, 22 Preview
- This extension: 1.13.4

### Description
Output of the compiled javascript file, that contains an exported function, does not work.

### Steps to recreate
1. Create a project (doesn't matter, which type)
2. Add a javascript file with this content 
`export function testFunction() { }`
3. Compile the file with this extension
4. Execute the output file in the browser (doesn't matter, if it's minified or not)

### Current behavior
Compile a javascript file and let the browser load the file. Browser gives an error 'Uncaught ReferenceError: exports is not defined'.

### Expected behavior
Compiled file, contains statements, that aren't necessary for javascript files.
The output of the compiled file is this:

```
"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.testFunction = testFunction;

function testFunction() {}

```

`Object.defineProperty()` and `exports.testFunction` are too much.

Or can i change/set properties, to "modify" the output, like the type of the compilation process as example es6 or es5.
I searched for those properties, but i dont found something.

**Comment by Fireblade954** [comment]
Any news on the new version?

**Comment by failwyn** [comment]
Since Bundler & Minifier handled this use case, I'm gonna keep it on the back burner for now; if Bundler & Minifier doesn't solve your issue, let me know, and I can take another look.

**Comment by alex-jitbit** [comment]
Having the same problem. Worked with Mads in 2019, stopped working in 2022

**Comment by failwyn** [comment]
This appears to be the expected output when using Babel to transform this Javascript; the extension Compiles/Transforms the file, then minifies the transformation if requested; if only minification is expected, I think Bundler & Minifier is the proper extension. If anyone disagrees, please let me know, I have no problem reopening the issue to take another look.

https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs

@Fireblade954 @reneduesmann
