### ISSUE TITLE
v1.14.9 doesn't work in VS versions earlier than 17.4

### ISSUE THREAD

**Issue by wg-davegriffiths** [failwyn/WebCompiler#61]
### Installed product versions
Visual Studio: 2022 Enterprise 17.2.6
This extension: 1.14.9

### Description
Extension fails to load correctly on versions previous to 17.4.  In enterprise environments, updates are controlled so quite likely not to be running the latest version.

### Current behavior
When installed on VS versions other than 17.4, the extension fails with this error at startup (logged in ActivityLog.xml):

`SetSite failed for package [WebCompilerInitPackage]Source: 'WebCompilerVsix' Description: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=17.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.`

Appears it is tied to v 17.4 of VS threading library and SDK, so earlier (or later) VS versions fail to find this. 

### Expected behavior
Work on all VS 2022 versions

**Comment by wg-davegriffiths** [comment]
Thanks for the quick response!

**Comment by failwyn** [comment]
1.14.9.2 is now available, sorry for the inconvenience.
