### ISSUE TITLE
The 'WebCompilerInitPackage" package did not load correctly.

### ISSUE THREAD

**Issue by TJSpilman** [failwyn/WebCompiler#62]
### Installed product versions
- Visual Studio: 2022 Pro 17.3.6
- This extension: 1.14.9.1

### Description
After updating to the latest version of Web Compiler 2022+ i get an error "The 'WebCompilerInitPackage" package did not load correctly. "when starting Visual Studio 2022.

When trying to compile I get another error: "There is an error in the compilerconfig.json" and a few seconds later VS2022 crashes.

Log from my VS:

SetSite failed for package [WebCompilerInitPackage]Source: &apos;WebCompilerVsix&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=17.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=17.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Threading, Version=17.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A; at WebCompilerVsix.WebCompilerInitPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)&#x000D;&#x000A; at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass21_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A; at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A; at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A; at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x

**Comment by lomla** [comment]
Hello, I got the same issue.

**Comment by lockeStewart** [comment]
Same issue here

**Comment by Meijer-A** [comment]
Hi same here. I just got the error

**Comment by TJSpilman** [comment]
Fixed issue by updating VS2022 to 17.4.2!

**Comment by failwyn** [comment]
I'm building a new release right now with the Microsoft.VisualStudio.* nuget packages downgraded to the lowest 17 version; previously the vsix was built using the pre release versions and I wanted to upgrade those, I just didn't realize that would make Visual Studio 2022 version 17.4 required; sorry for the bad release.

**Comment by mucahitbugday** [comment]
the problem seems to be fixed thanks

**Comment by mucahitbugday** [comment]
Is there an error in the javascript compiler?

visual sutudio version: 17.4.2
Package version: 1.14.9.2

**Comment by failwyn** [comment]
@mucahitbugday Not that I know of; if you are having an issue compiling something, just open a new issue and provide as many details as possible and I will look into it.

**Comment by shavla** [comment]
Hello, 1.14.9.2 is not visible and have same issue.
visual studio version 17.4.2
![Screenshot 2022-12-02 115051](https://user-images.githubusercontent.com/57368636/205242946-f0dfb5be-caf1-4311-95d4-821564a5d3bf.png)

**Comment by failwyn** [comment]
1.14.9.1 is the latest version on github, the change required to fix this
issue didn't change any code in the nuget package, so I didn't rebuild and
deploy the nuget package.
