### ISSUE TITLE
Version 14.9.2 changes "0 none" to "0 0" during minification

### ISSUE THREAD

**Issue by ji-gr** [failwyn/WebCompiler#64]
### Installed product versions
- Visual Studio: 2022 Enterprise 17.4.2
- This extension: 14.9.2

### Description
Minifier changes less/css content, from valid css to invalid css.min
border: 0 none;
to
border: 0 0;

### Steps to recreate
1. Create file test.less with content 
2. set compilerconfig.json to compile and minify this file 
4. create test.less content as
body {
    border: 0 none;
}
6. compile (and minify) test.less

### Current behavior
Compiler creates test.css
body {
    border: 0 none;
}
while minification creates test.css.min
body{border:0 0;}

### Expected behavior
The minification should not interfere with the css file and replace "none" with "0".

**Comment by failwyn** [comment]
Sounds like an issue with NUglify; did it work in 1.14.8?

**Comment by failwyn** [comment]
I'll release a new version once [this](https://github.com/trullock/NUglify/issues/343) issue is fixed in NUglify.

**Comment by failwyn** [comment]
created a pull request to fix the issue

**Comment by failwyn** [comment]
My pull request has been merged, just waiting on a new release and I’ll update WebCompiler.

**Comment by MichelJansson** [comment]
NUglify 1.20.4 have been released that should fix this 👍

**Comment by failwyn** [comment]
I’ll check it tomorrow and get a new release out asap.

**Comment by failwyn** [comment]
@ji-gr - I just uploaded 1.14.10, you can close this if it resolves the issue for you.

**Comment by ji-gr** [comment]
Thanks, works as expected, closing the issue.
