### ISSUE TITLE
Validation warning shown for valid css, how to turn this off ?

### ISSUE THREAD

**Issue by dotnetshadow** [failwyn/WebCompiler#78]
Hi there, thanks for your time and effort

### Installed product versions
- Visual Studio: 2022 Professional
- This extension: 1.14.11

### Description
Validation waning shown for valid scsss
If I turn validation off through Text Editor -> SCSS -> Advanced -> Enable validation then no warning is shown

### Steps to recreate
1. Create a scss with a **grid-template-areas** property

### Current behavior

![image](https://user-images.githubusercontent.com/296247/231125526-8d982777-c60a-4aa6-a916-f78823baf85a.png)

![image](https://user-images.githubusercontent.com/296247/231125465-80278718-fb0e-44a7-bc1b-c1edcc841b12.png)

Other people have reported this
https://stackoverflow.com/questions/69970340/how-to-set-grid-template-areas-in-sass-node-sass

### Expected behavior
There shouldn't be an warning. Is there any way to prevent warnings shown for certain validation warnings, I don't want to disable all validation warnings

**Comment by failwyn** [comment]
I believe that error is produced by Visual Studio, I run into a lot of issueswith the Visual Studio Text Editor showing errors for valid and functional code.
