### ISSUE TITLE
Move to Dart-sass from Node-sass

### ISSUE THREAD

**Issue by XzaR90** [failwyn/WebCompiler#8]
### Installed product versions
- Visual Studio: 2022

### Description
Node-sass is deprecated, we should use Dart-sass
https://itnext.io/the-css-preprocessor-dilemma-node-sass-or-dart-sass-32a0a096572

### Current behavior
A deprecated SASS compiler is used.

### Expected behavior
None deprecated version of SASS compiler should be used.

**Comment by james-d-elliott** [comment]
Related: https://github.com/madskristensen/WebCompiler/pull/479

**Comment by XzaR90** [comment]
Maybe I could fix it, i will see tomorrow.

**Comment by failwyn** [comment]
@XzaR90 Thanks for the pull request, I'm away for the weekend, but I'll take a look at this as soon as I get back!

**Comment by XzaR90** [comment]
I see, yes the quite-deps would be required for backward compatibility. Yes probably a preview version would be nice to test it out. I am going to migrate to bootstrap 5 so I could try it out as well.

**Comment by XzaR90** [comment]
Don't forget to update the changelog.

**Comment by failwyn** [comment]
I'm gonna update that and remove the Preview flag as soon as we see if the move to Dart Sass is generally accepted.
