### ISSUE TITLE
node-sass is now deprecated

### ISSUE THREAD

**Issue by garyhuntddn** [failwyn/WebCompiler#83]
### Description
The NPM package node-sass is now deprecated - see https://www.npmjs.com/package/node-sass.

It would be preferable to migrate to dart-sass for future compatibility.

Unfortunately this will probably involve a lot of testing and we all know how time-consuming that can be.

**Comment by failwyn** [comment]
We migrated to Dart Sass November 24, 2021.

**Comment by garyhuntddn** [comment]
That’s great news, but see line 19 of build/build.cmd

**Comment by failwyn** [comment]
Node-Sass is still there for backwards compatibility

[https://github.com/failwyn/WebCompiler/blob/master/CHANGELOG.md#1145](https://github.com/failwyn/WebCompiler/blob/master/CHANGELOG.md#1145)
