### ISSUE TITLE
Different/incorrect output when extending a class

### ISSUE THREAD

**Issue by AlanWaiss** [failwyn/WebCompiler#9]
### Installed product versions
- Visual Studio: 2020 Enterprise
- This extension: 1.13.4

### Description
Incorrect/different SCSS output

### Steps to recreate
Using this scss:
```
%tb {
	border: solid 1px #666;
	&:focus {
		border-color: #000;
	}
}
@each $type in text, search, email, number, tel, time, password {
	input[type=#{$type}] {
		@extend %tb;
	}
}
```

### Current behavior
It's producing output:
```
input[type=text], input[type=search], input[type=email], input[type=number], input[type=tel], input[type=time], input[type=password], input[type^=date] {
	border: solid 1px #666;
}
  input:focus[type=text], input:focus[type=search], input:focus[type=email], input:focus[type=number], input:focus[type=tel], input:focus[type=time], input:focus[type=password], input:focus[type^=date] {
    border-color: #000; }
```

### Expected behavior
The :focus pseudo class should be after the attribute specifier. It was this way in the VS2019 extension.
```
input[type=text], input[type=search], input[type=email], input[type=number], input[type=tel], input[type=time], input[type=password], input[type^=date] {
	border: solid 1px #666;
}
  input[type=text]:focus, input[type=search]:focus, input[type=email]:focus, input[type=number]:focus, input[type=tel]:focus, input[type=time]:focus, input[type=password]:focus, input[type^=date]:focus {
    border-color: #000; }
```

This could be related to the Dart vs Node issue - I'm not sure what the differences are.

**Comment by XzaR90** [comment]
Maybe you could try #10 #8 and see if it works?

**Comment by failwyn** [comment]
@AlanWaiss - Do you know if this works in the Visual Studio 2019 version of WebCompiler?

**Comment by AlanWaiss** [comment]
It does work in the 2019 version. I actually found this when I was testing VS2022 to see if it works with my existing solution. I noticed a difference when I recompiled my scss.

**Comment by failwyn** [comment]
It looks like #8 addressed this issue.
