### ISSUE TITLE
VS2022 Keeps Crashing

### ISSUE THREAD

**Issue by BrokenShoeLace** [failwyn/WebCompiler#91]
VS 17.8.1 Ent.
Installed, restarted the computer and began using SCSS.
Each time I click SAVE, VS2022 crashes (closes). I open again and the same over & over again.
I remove the extension, add back and the same thing continues.

![WebCompiler Crash](https://github.com/failwyn/WebCompiler/assets/65475317/d6193570-d4d7-438a-9c5a-70cc91a51e66)

**Comment by failwyn** [comment]
Can you list your machine config? OS, Ram, Processor, Visual Studio 2022 version? Also, if you could locate and post the Visual Studio crash log, I can take a look at that.

// It's working as expected for my team on the latest version of 2022

**Comment by BrokenShoeLace** [comment]
128 Gb
20 Tb Raided
NVidia 4080 Graphics
Visual Studio 2022 Enterprise with MSDN (latest version updated yesterday)
Windows 11 Enterprise

It seems after using Bing a different workaround for another bug works for me:

Delete the folder in TEMP, but twice a day for months is getting boring. To quote a few others' comments:

When is it going to be fixed?
I cannot believe it hasnt been fixed yet.

Dont worry, as I have been waiting years for Microsoft to upgrade SCSS to the latest version of DART:

https://developercommunity.visualstudio.com/t/Dart-SCSS-Support-Request/1388380

That's a different story

**Comment by failwyn** [comment]
Were you able to get the Visual Studio crash report?On Dec 8, 2023, at 11:51 PM, Broken Shoelace ***@***.***> wrote:﻿
128 Gb
20 Tb Raided
NVidia 4080 Graphics
Visual Studio 2022 Enterprise with MSDN (latest version updated yesterday)
Windows 11 Enterprise
It seems after using Bing a different workaround for another bug works for me:
Delete the folder in TEMP, but twice a day for months is getting boring. To quote a few others' comments:
When is it going to be fixed?
I cannot believe it hasnt been fixed yet.
Dont worry, as I have been waiting years for Microsoft to upgrade SCSS to the latest version of DART:
https://developercommunity.visualstudio.com/t/Dart-SCSS-Support-Request/1388380
That's a different story

**Comment by BrokenShoeLace** [comment]
No, do not still have crash report. I will only send crash reports to Microsoft

**Comment by failwyn** [comment]
I can't do much without being able to replicate the issue or identify the it with the crash report.

**Comment by BrokenShoeLace** [comment]
Not being funny but this is happening to many users out there & as one user put it: hasn't this been resolved yet?

Its about time, Microsoft created their own solution as there has been a need for it for many years.

Mads was good in creating what you took over but it has always had it's issues. I think the solution is finding how dart scss can be used by VS, so people can say USE rather than IMPORT etc. Basically, you are maintaining something for an obsolete version of SCSS.

Personally, I am writing cmdlets for Powershell right now in C# so have no requirements for the Web Compiler. That will change in a few months, but not now.

**Comment by failwyn** [comment]
The extension supports both Dart and Node SASS. 

It’s not fixed because you can’t fix what you can’t reproduce, and you aren’t willing to share your crash reports… If a lot of people were having this issue, they’d be commenting here and would hopefully contribute to identifying the problem. 

// I’m gonna close the issue if you aren’t willing to help identify what’s causing your crash.

**Comment by BrokenShoeLace** [comment]
Do a search for this app crashing due to the folder existing in the temp and read the forums. This is how I found a workaround.

WebCompiler is already uninstalled.

Think, why is it copying and attempting to overwrite a locked file and go from there.

There are more important things need doing than waiting for a fix.

**Comment by failwyn** [comment]
You’re more than welcome to submit a pull request since it’s such an easy fix…
